### ISSUE TITLE
Tag 1.0.9 is not updated with master

### ISSUE THREAD

**Issue by tiagojsalmeida** [muaz-khan/DetectRTC#10]
If you bower install with tag 1.0.9 it will fail on IE10.
Please create a new tag with the updated master branch.

**Comment by bbenezech** [comment]
1.2.6 has been released since.
@muaz-khan you can close this issue and bump 1.2.7 with 3945a9b0047046e9538879bb2ab74bfe405bb397 ?

Thanks !
