### ISSUE TITLE
Doesn't handle refusal properly in firefox

### ISSUE THREAD

**Issue by mvduin** [muaz-khan/DetectRTC#19]
If I dismiss the permission dialog using the close-button (which turns out to be equivalent to selecting "not now" from the popup menu) then the entire results section never shows at all.

If I explicitly choose "don't share" from the popup menu then the results section correctly shows the number of mics and cams, but all of them have the description string "Please invoke getUserMedia once.".

DetectRTC v1.27
Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0 Iceweasel/44.0.2

**Comment by muaz-khan** [comment]
Fixed.
