### ISSUE TITLE
Initial release version

### ISSUE THREAD

**Issue by bennycode** [muaz-khan/DetectRTC#2]
Hey Muaz,

I am very happy to see this library here! In order to lock it's dependency to a specific version it would be great if you could create a release version here on GitHub.

Thanks for the bower support!

Benny

**Comment by ghost** [comment]
It's already there :)

**Comment by bennycode** [comment]
Yes. Because I asked for it. Wasn't there when I requested it. So issue can be closed. Thanks Muaz! :+1:
