### ISSUE TITLE
checkDeviceSupport doesn't call the callback when canEnumerate is false

### ISSUE THREAD

**Issue by michaelstephendavies** [muaz-khan/DetectRTC#21]
Hi

At [DetectRTC.js:598](https://github.com/muaz-khan/DetectRTC/blob/master/DetectRTC.js#L598) you return early when `canEnumerate` is false, but here you don't call the callback. This is different from line 611 where you do call the callback when `navigator.enumerateDevices` does not exist. This causes the callback of `DetectRTC.load` to never be called in some browsers (specifically IE10).

**Comment by nasivuela** [comment]
+1
Same happens in Safari, we could add a quick fix to trigger the callback of load method if devices can't be enumerated.

```
if (!canEnumerate || !navigator.enumerateDevices) {
  if (callback) {
    callback();
  }
  return;
}
```

I also though about adding a feature to return accurated info for this case, maybe:

```
if (!canEnumerate || !navigator.enumerateDevices) {
  var hasMicrophone = 'undefined';
  var hasSpeakers = 'undefined';
  var hasWebcam = 'undefined';
  if (callback) {
    callback();
  }
  return;
}
```

What do you think?
