### ISSUE TITLE
DetectRTC.load() "has*" properties are not reset to false

### ISSUE THREAD

**Issue by amillet** [muaz-khan/DetectRTC#26]
Hey!

When calling DetectRTC.load() and webcam is plugged, DetectRTC.hasWebcam value is set to true. But when unplugging my webcam and calling DetectRTC.load(), DetectRTC.hasWebcam value is still set to true.

I purpose you to set hasMicrophone/hasSpeakers/hasWebcam to false as you set audioInputDevices = []; ... in the function getIPs(callback). What do you think ?

**Comment by muaz-khan** [comment]
You can use looper or setInterval to reset properties.

```javascript
(function looper() {
     DetectRTC.load(function() {
         setTimeout(looper, 3000); // 3 seconds
     });
})();
```
