### ISSUE TITLE
Getting DetectRTC is undefined issue

### ISSUE THREAD

**Issue by amitsbaghel** [muaz-khan/DetectRTC#32]
Getting this issue on Internet Explorer and Safari 

Unable to get property 'prototype' of undefined or null reference

on Line no 840 approx

   if ('createMediaStreamSource' in window[item].prototype) {
                webAudio.isCreateMediaStreamSourceSupported = true;
            }

and then I get 

ReferenceError: 'DetectRTC' is undefined

**Comment by muaz-khan** [comment]
Fixed.
