### ISSUE TITLE
Which browsers does this work in?

### ISSUE THREAD

**Issue by cyorobert** [muaz-khan/DetectRTC#33]
I couldn't find browser compatibility in the documentation. Can you please advise? Very useful library btw, great job!

**Comment by muaz-khan** [comment]
1. Chrome (all platforms including mobile devices)
2. Firefox (all platforms including mobile devices)
3. Opera (all platforms including mobile devices)
4. Safari (all platforms including mobile devices)
5. Microsoft Edge (Windows 10)
