### ISSUE TITLE
Deactivated IndexedDB causes InvalidStateError

### ISSUE THREAD

**Issue by SkaveRat** [muaz-khan/DetectRTC#36]
[This call](https://github.com/muaz-khan/DetectRTC/blob/5aff56c2fbcc55ef5793926c7389f37467502cf5/dev/detectPrivateBrowsing.js#L49) to window.indexedDB causes following exception:

`InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.`

if you have deactivated indexedDB on firefox (not default, but possible by plugins etc).

To replicate:
set `dom.indexedDB.enabled` in about:config to false and call `window.indexedDB` from JS console.

**Comment by SkaveRat** [comment]
well, that has to be the fastest issue I've opened yet :+1: 

any idea when it will be on npm?

**Comment by blablapolicja** [comment]
reopen this issue, please. the bug can be replicated on Firefox 55.0.3 in Private mode
try/catch block doesn't work
```javascript
try {
   db = window.indexedDB.open('test');
   db.onerror = function() {
      return true;
   };
} catch (e) {
   isPrivate = true;
}
```

possible solution https://stackoverflow.com/a/45672895/4019802
