### ISSUE TITLE
DetectRTC causes `window` to be defined in nodejs environments

### ISSUE THREAD

**Issue by ianwremmel** [muaz-khan/DetectRTC#37]
https://github.com/muaz-khan/DetectRTC/blob/master/DetectRTC.js#L33 defines window as a property of global, which causes checks like `typeof window === 'undefined'` to run browser code in node environments.

**Comment by muaz-khan** [comment]
WontFix. Because grunt fails if we ignore `window` object. If you've a solution, please make a pull request.

**Comment by ianwremmel** [comment]
Can you explain what you mean by "grunt fails"? I just commented out the offending line (which now seems to be [39](https://github.com/muaz-khan/DetectRTC/blob/master/DetectRTC.js#L39)) and grunt still successfully built DetectRTC.js.

I also tried running `npm test` according to the README, but got

```bash
$ npm test

> detectrtc@1.3.4 test /Users/ian/projects/DetectRTC
> echo 'Error: no test specified'

Error: no test specified
```

Finally, I modified index.html to point at `./DetectRTC.js` instead of the cdn-hosted one and it still appears to work.

**Comment by muaz-khan** [comment]
This one fails:

* https://github.com/muaz-khan/DetectRTC/blob/master/npm-test.js

```sh
node npm-test.js
```

i.e. DetectRTC fails to run inside the `node.js` environment.
