### ISSUE TITLE
IE version detection is incorrect

### ISSUE THREAD

**Issue by zzxx53** [muaz-khan/DetectRTC#50]
In IE11, the browser version is reported as 5. Even though IE doesn't support WebRTC, it would be nicer to make sure the version reported is correct.

**Comment by zzxx53** [comment]
The current logic for detecting IE version (looking for the string after MSIE) only works for IE versions up to 10; for IE 11 one should be looking at the string after "rv".

**Comment by zzxx53** [comment]
Fixed with PR 51: 
https://github.com/muaz-khan/DetectRTC/pull/51

**Comment by muaz-khan** [comment]
Merged. Thanks.
