### ISSUE TITLE
iOS 11 DetectRTC.browser.isSafari Gives erroneous information in Chrome and Firefox

### ISSUE THREAD

**Issue by vakya** [muaz-khan/DetectRTC#63]
Perdon for my english.

I use Ipad Air with Safari, Chrome and Firefox. When I execute the DetectRTC.browser.isSafari sentence, in the three browsers it gives the same result => true.

Thank you very much for the great job you have done.

**Comment by dan24678** [comment]
This regular expression combination tests for Safari and excludes FF and Chrome when they are found running on iOS:  

  isSafari: /^((?!chrome|android).)*safari/i.test(navigator.userAgent || '') &&
    !(/CriOS/i.test(navigator.userAgent || '')) &&
    !(/FxiOS/i.test(navigator.userAgent || ''))
