### ISSUE TITLE
TypeError: osVersion is null while using firefox devtools in iphone response mode

### ISSUE THREAD

**Issue by piotrrussw** [muaz-khan/DetectRTC#92]
I've got error on firefox while working in responsive mode with any of the iOS device selected.
This doesn't occur on Android. Error is [https://github.com/muaz-khan/DetectRTC/blob/master/DetectRTC.js#L471](here).
Could you add check if osVersion has this elements in Array?

**Comment by lordenas** [comment]
I have a same issues

**Comment by piotrrussw** [comment]
I've added PR with fix for this issue:
https://github.com/muaz-khan/DetectRTC/pull/93
